# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Step 1 - Checkout github repository
        uses: actions/checkout@v3

      - name: Step 2- Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Step 3 - Build with Maven project - so jar is created
        run: mvn -B package --file pom.xml
        
      - name: Step 4 - List out what's in current directory.
        run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              ls -la
         elif [ "$RUNNER_OS" == "Windows" ]; then
              dir
         elif [ "$RUNNER_OS" == "macOS" ]; then
              ls -la
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash
        
      - name: Step 5 - What's in target folder?
        run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              cd target
              ls -la
         elif [ "$RUNNER_OS" == "Windows" ]; then
              cd target
              dir
         elif [ "$RUNNER_OS" == "macOS" ]; then
              cd target
              ls -la
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cheers2019:latest


#publish:
  #needs: build
